### ISSUE TITLE
Can the tests be executed / pass the vertifier?

### ISSUE THREAD

**Issue by Vinc0682** [helios-decompiler/decompiler-vulnerabilities-and-bugs#7]
The bug score should contain weather the test can be executet (or pass the vertifier) since it has a signifact impact weather it can be used to avoid decompiling an application or not...

**Comment by samczsun** [comment]
Whether a decompiler produces syntactically valid code is not as important as whether the code is actually understandable. Just by renaming identifiers you can guarantee non-verifiable code but that's not necessarily a bug within the decompiler
